# Generated by Django 2.2.16 on 2020-11-03 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_broker'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_broker',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_private',
            field=models.BooleanField(default=True),
        ),
    ]
