# Generated by Django 2.2.16 on 2020-11-07 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20201103_2105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_broker',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_private',
        ),
        migrations.AddField(
            model_name='customuser',
            name='account',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='customuser',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
